# define a variable for the report's folder name using timestamp as suffix
export DIR="DemoAppWS_TestReport_"$(date +"%Y%m%d%H%M") ;

# run the tests via maven with additional arguments to generate report
mvn clean install surefire-report:report-only site -DgenerateReports=false;

# generate test-reports folder and a subfolder with the name as defined in DIR variable above
mkdir -p "test-reports/$DIR" ;

# when running with maven a target folder is generated automatically. copy its content to the test-report folder
cp -a target/site/. test-reports/$DIR/ ;
cp -a target/surefire-reports/. test-reports/$DIR/ ;

# generate a logs subfolder and copy there all the log files that are generated by soapui
mkdir -p "test-reports/$DIR/logs";
mv *.log test-reports/$DIR/logs ;
mv soapui.log.* test-reports/$DIR/logs

# remove target folder
rm -rf target && rm *.log && rm soapui.log.* ;



